'use client';
import {useState} from 'react';
import {Box, Wrench, Cable, LayoutDashboard, MapPin, ShieldCheck} from 'lucide-react';
const content = [
 {name:'Assets',icon:Box,title:'Every asset. A clearer picture.',description:'Equipment, locations and status in one workspace.',stats:[['Assets registered','24'],['Locations','3'],['Operational','22']],rows:[['Reception terminal','Main entrance','Operational'],['Cooling system','Technical area','Maintenance'],['Access controller','First floor','Operational']]},
 {name:'Maintenance',icon:Wrench,title:'Make room for preventive work.',description:'A preview of the planned maintenance experience.',stats:[['Planned tasks','8'],['In progress','2'],['Completed','14']],rows:[['Monthly equipment inspection','Technical team','Scheduled'],['Cooling system service','Maintenance','In progress'],['Safety check','Operations','Completed']]},
 {name:'Integrations',icon:Cable,title:'Bring your tools together.',description:'Illustrative workflows, subject to integration scope.',stats:[['Sample workflows','3'],['Systems per workflow','2'],['Available connectors','TBC']],rows:[['Incident notifications','Team communication','Concept'],['Stock updates','Inventory tools','Concept'],['Maintenance reports','Reporting','Concept']]}
];
export function ProductPreview(){const [active,setActive]=useState(0);const m=content[active];return <div className="product-window"><div className="window-top"><span className="window-lights"><i/><i/><i/></span><span>TSUNEXA WORKSPACE</span><span>Illustrative data</span></div><div className="product-body"><aside className="product-sidebar"><span className="wordmark">Tsunexa</span><p>Demo organisation</p><div className="module-buttons" aria-label="Preview modules">{content.map((item,i)=><button key={item.name} aria-pressed={active===i} onClick={()=>setActive(i)}><item.icon size={17}/>{item.name}</button>)}</div><div className="product-side-note"><ShieldCheck size={18}/> Built around<br/>your organisation</div></aside><div className="product-content" aria-live="polite"><div className="product-breadcrumb"><LayoutDashboard size={14}/> Workspace / {m.name}<span className="preview-badge">PRODUCT PREVIEW</span></div><h3>{m.title}</h3><p>{m.description}</p><div className="preview-stats">{m.stats.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="preview-table-wrap"><table><caption>{active===0?'Asset overview':active===1?'Maintenance overview':'Workflow concepts'}</caption><thead><tr><th>Name</th><th>Area</th><th>Status</th></tr></thead><tbody>{m.rows.map(([name,area,status])=><tr key={name}><td><Box size={15}/>{name}</td><td>{area}</td><td><span className={status==='Maintenance'||status==='In progress'?'status amber':'status'}>{status}</span></td></tr>)}</tbody></table></div><div className="preview-footer"><MapPin size={14}/> Your workspace, connected.<span>Example only · Not live account data</span></div></div></div></div>}
